blueprints/guest_bp.py
import uuid

import bcrypt
from flask import Blueprint, redirect, url_for, request, render_template, flash
from flask_login import login_user, login_required, logout_user, current_user

from forms import RegisterForm, LoginForm
from models import User, db

guest_blueprint = Blueprint('guest_views', __name__, template_folder='templates')


def redirect_if_authenticated(username=None):
    if current_user.is_authenticated:
        return redirect(url_for('user_views.dashboard', username=username or current_user.username))


@guest_blueprint.route('/')
def redir():
    return redirect(url_for('guest_views.home'))


@guest_blueprint.route('/home')
def home():
    return render_template('guest/home.html')


@guest_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # if user is already logged in, redirect to dashboard
    redirect_response = redirect_if_authenticated()
    if redirect_response:
        return redirect_response

    # if user presses login button
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        # check if user exists
        user = User.query.filter_by(username=form.username.data).first()
        # if user does not exist, flash error and redirect to login page
        if user is None:
            flash("The account does not exist.", category='error')
            return render_template('guest/login.html', form=form, error="The account does not exist.")
        # check if password matches
        if bcrypt.checkpw(form.password.data.encode('utf-8'), user.password.encode('utf-8')):
            login_user(user)
            flash("Logged in", category='success')
            return redirect(url_for('user_views.dashboard', username=user.username))
        # if password does not match, flash error and redirect to login page
        flash("Incorrect Password", category='error')
        return render_template('guest/login.html', form=form, error="Invalid email or password")

    return render_template('guest/login.html', form=form)


@guest_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # if user is already logged in, redirect to dashboard
    redirect_response = redirect_if_authenticated()
    if redirect_response:
        return redirect_response

    # if user presses register button
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        # check if user exists
        user = User.query.filter_by(username=form.username.data).first()
        email = User.query.filter_by(email=form.email.data).first()
        if user or email:
            # if user exists, flash error and redirect to register page
            flash("Account already exists", category='error')
            return render_template('guest/register.html', form=form, error="Account already exists")
        else:
            # if user does not exist, create user and redirect to login page
            new_user = User(
                user_id=str(uuid.uuid4()),
                username=form.username.data,
                email=form.email.data,
                password=bcrypt.hashpw(form.password.data.encode('utf-8'), bcrypt.gensalt()),
                role='user'
            )
            db.session.add(new_user)
            db.session.commit()
            flash("Account created successfully.", category='success')
            return redirect(url_for('guest_views.login'))
    return render_template('guest/register.html', form=form)


@guest_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logged out", category='success')
    return redirect('/')

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Page title -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Flask Notes">
    <meta property="og:description" content="Flask Notes, a note taking app built with Flask">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheet/styles.css') }}">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css"
          rel="stylesheet" type='text/css'>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark sticky-top" id="main-nav">
    {% if not current_user.is_authenticated %}
        <a class="navbar-brand" href="{{ url_for('guest_views.home') }}">Flask Notes</a>
    {% elif current_user.is_authenticated %}
        <a class="navbar-brand"
           href="{{ url_for('user_views.dashboard', username=current_user.username) }}">
            <span id="greeting"></span>, {{ current_user.username }}</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto right">
            {% if current_user.is_authenticated %}
                <li class="nav-item active">
                    <a title="Logout" class="nav-link" href="#" onclick="logout()">Logout</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a title="Login" class="nav-link" href="{{ url_for('guest_views.login') }}">Login</a>
                </li>
                <li class="nav-item active">
                    <a title="Register" class="nav-link" href="{{ url_for('guest_views.register') }}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- Error Message -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <!-- Success message (Green) -->
            {% if category == 'success' %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            
            <!-- Warning message (Yellow) -->
            {% elif category == 'warning' %}
                <div class="alert alert-warning" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            
            <!-- Error message (Red) -->
            {% elif category == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

<!-- Page Content -->
{% block content %}{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='script/script.js') }}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const greetingElement = document.getElementById('greeting');
        if (greetingElement) {
            greetingElement.textContent = greetTimeOfDay();
        }
    });
</script>
</body>
</html>