blueprints/user_bp.py
import uuid
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from forms import AddNoteForm, EditNoteForm
from models import Note, db
from rbac import role_required

user_blueprint = Blueprint('user_views', __name__, template_folder='templates')


@user_blueprint.route('/dashboard/user/<username>', methods=['GET'])
@login_required
@role_required('user')
def dashboard(username):
    notes = Note.query.filter_by(user_id=current_user.user_id).all()
    fave_notes = Note.query.filter_by(user_id=current_user.user_id, favorite=True).all()
    for note in notes:
        note.date_created = note.date_created.strftime("%Y/%m/%d %H:%M:%S")
        note.date_created = note.date_created.split(' ')
        note.date_created[0] = datetime.strptime(note.date_created[0], "%Y/%m/%d").strftime("%B %d, %Y")
        note.date_created = ' '.join(note.date_created)

    return render_template('user/dashboard.html', notes=notes, fave_notes=fave_notes)


@user_blueprint.route('/add-note', methods=['GET', 'POST'])
@login_required
@role_required('user')
def add_note():
    form = AddNoteForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        new_note = Note(
            note_id=str(uuid.uuid4()),
            title=form.title.data,
            content=form.content.data,
            date_created=datetime.now().strftime("%Y/%m/%d %H:%M:%S"),
            user_id=current_user.user_id
        )

        db.session.add(new_note)
        db.session.commit()
        flash("Note added ✅", category='success')
        return redirect(url_for('user_views.dashboard', username=current_user.username))

    return render_template('user/addnote.html', form=form)


@user_blueprint.route('/edit-note/<note_id>', methods=['GET', 'POST'])
@login_required
@role_required('user')
def edit_note(note_id):
    form = EditNoteForm(request.form)
    note = Note.query.filter_by(note_id=note_id).first()
    if request.method == 'POST' and form.validate_on_submit():
        note.title = form.edit_title.data
        note.content = form.edit_content.data,
        note.date_created = datetime.now().strftime("%Y/%m/%d %H:%M:%S")
        db.session.commit()
        flash("Note updated 👍", category='success')
        return redirect(url_for('user_views.dashboard', username=current_user.username))
    return render_template('user/editnote.html', form=form, note=note)


@user_blueprint.route('/delete-note/<note_id>', methods=['GET'])
@login_required
@role_required('user')
def delete_note(note_id):
    note = Note.query.filter_by(note_id=note_id).first()
    db.session.delete(note)
    db.session.commit()
    flash("Note deleted 🗑️", category='success')
    return redirect(url_for('user_views.dashboard', username=current_user.username))


@user_blueprint.route('/favorite-note/<note_id>', methods=['GET', 'POST'])
@login_required
@role_required('user')
def favorite_note(note_id):
    note = Note.query.filter_by(note_id=note_id).first()
    if note.favorite:
        note.favorite = False
        flash("Removed from favorites 💔", category='success')
    else:
        note.favorite = True
        flash("Saved to favorites 💖", category='success')

    db.session.commit()
    return redirect(url_for('user_views.dashboard', username=current_user.username))

templates/user/addnote.html
{% extends "base.html" %}
{% block title %}Add Note{% endblock %}
{% block content %}
    <div class="addnote-form-container">
        <form method="post" action="/add-note">
            <h2>Add note</h2>
            <!-- CSRF Protection -->
            {{ form.csrf_token }}

            <!-- Title input-->
            <div class="form-group">
                {{ form.title.label(class="form-label", for="addnote-title") }}
                {{ form.title(class="form-control", id="addnote-title", placeholder="Enter title") }}
            </div>

            <!-- Content input-->
            <div class="form-group">
                {{ form.content.label(class="form-label", for="addnote-content") }}
                {{ form.content(class="form-control", id="addnote-content", placeholder="Enter content") }}
            </div>

            <!-- Submit/Add note button -->
            <button title="Add note" type="submit" class="btn btn-primary">Add</button>

            <!-- Cancel button -->
            <a title="Cancel" class="btn btn-primary" href="{{ url_for('user_views.dashboard', username=current_user.username) }}"
               role="button">Cancel</a>
        </form>
    </div>

{% endblock %}

templates/user/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <!-- FAVORITES section-->
    <h2 class="dashboard_title">Favorites</h2>
    <div id="notes-container">
        {% for fave_note in fave_notes %}
            <div class="card" id="note-card">
                <div class="card-body">
                    <h4 class="card-title">{{ fave_note.title }}</h4>
                    <p class="card-text">{{ fave_note.content|replace('\n', '<br>')|safe }}</p>
                    <small class="card-text">Created at {{ fave_note.date_created }}</small><br><br>
                    <div id="note-actions">
                        <!-- EDIT note button -->
                        <a id="edit-note-button"
                           href="{{ url_for('user_views.edit_note', note_id=fave_note.note_id) }}">
                            <i title="Edit" class="fa fa-pencil-square fa-2x"></i>
                        </a>

                        <!-- DELETE note button -->
                        <a id="delete-note-button"
                           href="{{ url_for('user_views.delete_note', note_id=fave_note.note_id) }}"
                           onclick="return deleteNote()">
                            <i title="Delete" class="fa fa-trash fa-2x"></i>
                        </a>

                        <!-- FAVORITE/REMOVE FAVORITE note button -->
                        {% if fave_note.favorite == True %}
                            <a id="remove-favorite-note-button"
                               href="{{ url_for('user_views.favorite_note', note_id=fave_note.note_id) }}">
                                <i title="Remove from favorites" class="fa fa-heart fa-2x"></i>
                            </a>
                        {% else %}
                            <a id="favorite-note-button"
                               href="{{ url_for('user_views.favorite_note', note_id=fave_note.note_id) }}">
                                <i title="Add to favorites" class="fa fa-heart fa-2x"></i>
                            </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr>
    <!-- ALL NOTES section -->
    <h2 class="dashboard_title">My Notes</h2>
    <div id="notes-container">
    {% for note in notes %}
        <div class="card" id="note-card">
            <div class="card-body">
                <h4 class="card-title">{{ note.title }}</h4>
                <p class="card-text">{{ note.content|replace('\n', '<br>')|safe }}</p>
                <small class="card-text">Created at {{ note.date_created }}</small><br><br>
                <div id="note-actions">
                    <!-- EDIT note button -->
                    <a id="edit-note-button" href="{{ url_for('user_views.edit_note', note_id=note.note_id) }}">
                        <i title="Edit" class="fa fa-pencil-square fa-2x"></i>
                    </a>

                    <!-- DELETE note button -->
                    <a id="delete-note-button" href="{{ url_for('user_views.delete_note', note_id=note.note_id) }}"
                       onclick="return deleteNote()">
                        <i title="Delete" class="fa fa-trash fa-2x"></i>
                    </a>

                    <!-- FAVORITE/REMOVE FAVORITE note button -->
                    {% if note.favorite == True %}
                        <a id="remove-favorite-note-button"
                           href="{{ url_for('user_views.favorite_note', note_id=note.note_id) }}">
                            <i title="Remove from favorites" class="fa fa-heart fa-2x"></i>
                        </a>
                    {% else %}
                        <a id="favorite-note-button"
                           href="{{ url_for('user_views.favorite_note', note_id=note.note_id) }}">
                            <i title="Add to favorites" class="fa fa-heart fa-2x"></i>
                        </a>
                    {% endif %}

                </div>
            </div>
        </div>
    {% endfor %}
    <div id="notes-container">

    <!-- ADD note button -->
    <a id="add-note-button" href="{{ url_for('user_views.add_note') }}">
        <i title="Add note" class="fa fa-plus-circle fa-5x"></i>
    </a>

{% endblock %}

templates/user/editnote.html
{% extends "base.html" %}
{% block title %}Edit Note{% endblock %}
{% block content %}
    <div class="addnote-form-container">
        <form method="post" action="/edit-note/{{ note.note_id }}">
            <h2>Edit note</h2>
            <!-- CSRF Protection -->
            {{ form.csrf_token }}

            <!-- Title update input-->
            <div class="form-group">
                {{ form.edit_title.label(class="form-label", for="editnote-title") }}
                {{ form.edit_title(class="form-control", id="editnote-title", value=note.title) }}
            </div>

            <!-- Content update input-->
            <div class="form-group">
                {{ form.edit_content.label(class="form-label", for="editnote-content") }}
                {{ form.edit_content(class="form-control", id="editnote-content") }}
            </div>

            <!-- Submit/Edit note button -->
            <button title="Edit note" type="submit" class="btn btn-primary">Save changes</button>

            <!-- Cancel button -->
            <a title="Cancel" class="btn btn-primary" href="{{ url_for('user_views.dashboard', username=current_user.username) }}"
               role="button">Cancel</a>
        </form>
    </div>
    <script>
        document.querySelector('#editnote-content').value = `{{note.content}}`;
    </script>
{% endblock %}